/*
TwelveLabs Video Understanding API

Use the TwelveLabs Video Understanding API to extract information from your videos and make it available to your applications. The API is organized around REST and returns responses in the JSON format. It is compatible with most programming languages, and you can also use Postman or other REST clients to send requests and view responses. 

API version: 1.3.0
Contact: support@twelvelabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package twelvelabs

import (
	"encoding/json"
)

// checks if the BaseSegment type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BaseSegment{}

// BaseSegment An object that contains the embedding value of a segment. 
type BaseSegment struct {
	// An array of floating point numbers representing the embedding. You can use this array with cosine similarity for various downstream tasks. Note that the example response was truncated for brevity.
	Float []float32 `json:"float,omitempty"`
}

// NewBaseSegment instantiates a new BaseSegment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBaseSegment() *BaseSegment {
	this := BaseSegment{}
	return &this
}

// NewBaseSegmentWithDefaults instantiates a new BaseSegment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBaseSegmentWithDefaults() *BaseSegment {
	this := BaseSegment{}
	return &this
}

// GetFloat returns the Float field value if set, zero value otherwise.
func (o *BaseSegment) GetFloat() []float32 {
	if o == nil || IsNil(o.Float) {
		var ret []float32
		return ret
	}
	return o.Float
}

// GetFloatOk returns a tuple with the Float field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseSegment) GetFloatOk() ([]float32, bool) {
	if o == nil || IsNil(o.Float) {
		return nil, false
	}
	return o.Float, true
}

// HasFloat returns a boolean if a field has been set.
func (o *BaseSegment) HasFloat() bool {
	if o != nil && !IsNil(o.Float) {
		return true
	}

	return false
}

// SetFloat gets a reference to the given []float32 and assigns it to the Float field.
func (o *BaseSegment) SetFloat(v []float32) {
	o.Float = v
}

func (o BaseSegment) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BaseSegment) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Float) {
		toSerialize["float"] = o.Float
	}
	return toSerialize, nil
}

type NullableBaseSegment struct {
	value *BaseSegment
	isSet bool
}

func (v NullableBaseSegment) Get() *BaseSegment {
	return v.value
}

func (v *NullableBaseSegment) Set(val *BaseSegment) {
	v.value = val
	v.isSet = true
}

func (v NullableBaseSegment) IsSet() bool {
	return v.isSet
}

func (v *NullableBaseSegment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBaseSegment(val *BaseSegment) *NullableBaseSegment {
	return &NullableBaseSegment{value: val, isSet: true}
}

func (v NullableBaseSegment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBaseSegment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


