/*
TwelveLabs Video Understanding API

Use the TwelveLabs Video Understanding API to extract information from your videos and make it available to your applications. The API is organized around REST and returns responses in the JSON format. It is compatible with most programming languages, and you can also use Postman or other REST clients to send requests and view responses. 

API version: 1.3.0
Contact: support@twelvelabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package twelvelabs

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the VideoItemFailed type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VideoItemFailed{}

// VideoItemFailed An object that contains information about a video file that failed to import. 
type VideoItemFailed struct {
	// The name of the video file.
	Filename string `json:"filename"`
	// The date and time, in the RFC 3339 format (\"YYYY-MM-DDTHH:mm:ssZ\"), when the video was added to the import process.
	CreatedAt time.Time `json:"created_at"`
	// The error message explaining why the video failed to import.
	ErrorMessage string `json:"error_message"`
}

type _VideoItemFailed VideoItemFailed

// NewVideoItemFailed instantiates a new VideoItemFailed object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVideoItemFailed(filename string, createdAt time.Time, errorMessage string) *VideoItemFailed {
	this := VideoItemFailed{}
	this.Filename = filename
	this.CreatedAt = createdAt
	this.ErrorMessage = errorMessage
	return &this
}

// NewVideoItemFailedWithDefaults instantiates a new VideoItemFailed object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVideoItemFailedWithDefaults() *VideoItemFailed {
	this := VideoItemFailed{}
	return &this
}

// GetFilename returns the Filename field value
func (o *VideoItemFailed) GetFilename() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value
// and a boolean to check if the value has been set.
func (o *VideoItemFailed) GetFilenameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Filename, true
}

// SetFilename sets field value
func (o *VideoItemFailed) SetFilename(v string) {
	o.Filename = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *VideoItemFailed) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *VideoItemFailed) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *VideoItemFailed) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetErrorMessage returns the ErrorMessage field value
func (o *VideoItemFailed) GetErrorMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ErrorMessage
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value
// and a boolean to check if the value has been set.
func (o *VideoItemFailed) GetErrorMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ErrorMessage, true
}

// SetErrorMessage sets field value
func (o *VideoItemFailed) SetErrorMessage(v string) {
	o.ErrorMessage = v
}

func (o VideoItemFailed) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VideoItemFailed) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["filename"] = o.Filename
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["error_message"] = o.ErrorMessage
	return toSerialize, nil
}

func (o *VideoItemFailed) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"filename",
		"created_at",
		"error_message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVideoItemFailed := _VideoItemFailed{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVideoItemFailed)

	if err != nil {
		return err
	}

	*o = VideoItemFailed(varVideoItemFailed)

	return err
}

type NullableVideoItemFailed struct {
	value *VideoItemFailed
	isSet bool
}

func (v NullableVideoItemFailed) Get() *VideoItemFailed {
	return v.value
}

func (v *NullableVideoItemFailed) Set(val *VideoItemFailed) {
	v.value = val
	v.isSet = true
}

func (v NullableVideoItemFailed) IsSet() bool {
	return v.isSet
}

func (v *NullableVideoItemFailed) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVideoItemFailed(val *VideoItemFailed) *NullableVideoItemFailed {
	return &NullableVideoItemFailed{value: val, isSet: true}
}

func (v NullableVideoItemFailed) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVideoItemFailed) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


