/*
TwelveLabs Video Understanding API

Use the TwelveLabs Video Understanding API to extract information from your videos and make it available to your applications. The API is organized around REST and returns responses in the JSON format. It is compatible with most programming languages, and you can also use Postman or other REST clients to send requests and view responses. 

API version: 1.3.0
Contact: support@twelvelabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package twelvelabs

import (
	"encoding/json"
)

// checks if the InlineObject1AllOfPageInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InlineObject1AllOfPageInfo{}

// InlineObject1AllOfPageInfo An object that provides information about pagination.
type InlineObject1AllOfPageInfo struct {
	// The maximum number of items on each page. When grouping by video, this field represents the maximum number of videos per page. Otherwise, it represents the maximum number of video clips per page. 
	LimitPerPage *int32 `json:"limit_per_page,omitempty"`
	// A string representing the date and time, in the RFC 3339 format (\"YYYY-MM-DDTHH:mm:ssZ\"), that the page expires. 
	PageExpiresAt *string `json:"page_expires_at,omitempty"`
	// The total number of results. When grouping by video, this field represents the total number of video clips matching your query. Otherwise , this field represents the total number of videos. 
	TotalResults *int32 `json:"total_results,omitempty"`
	// When grouping by video, the platform return this field that shows the total number of video clips matching your query. 
	TotalInnerMatches *int32 `json:"total_inner_matches,omitempty"`
	// The unique identifier of the next page.
	NextPageToken *string `json:"next_page_token,omitempty"`
	// The unique identifier of the previous page.
	PrevPageToken *string `json:"prev_page_token,omitempty"`
}

// NewInlineObject1AllOfPageInfo instantiates a new InlineObject1AllOfPageInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineObject1AllOfPageInfo() *InlineObject1AllOfPageInfo {
	this := InlineObject1AllOfPageInfo{}
	return &this
}

// NewInlineObject1AllOfPageInfoWithDefaults instantiates a new InlineObject1AllOfPageInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineObject1AllOfPageInfoWithDefaults() *InlineObject1AllOfPageInfo {
	this := InlineObject1AllOfPageInfo{}
	return &this
}

// GetLimitPerPage returns the LimitPerPage field value if set, zero value otherwise.
func (o *InlineObject1AllOfPageInfo) GetLimitPerPage() int32 {
	if o == nil || IsNil(o.LimitPerPage) {
		var ret int32
		return ret
	}
	return *o.LimitPerPage
}

// GetLimitPerPageOk returns a tuple with the LimitPerPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject1AllOfPageInfo) GetLimitPerPageOk() (*int32, bool) {
	if o == nil || IsNil(o.LimitPerPage) {
		return nil, false
	}
	return o.LimitPerPage, true
}

// HasLimitPerPage returns a boolean if a field has been set.
func (o *InlineObject1AllOfPageInfo) HasLimitPerPage() bool {
	if o != nil && !IsNil(o.LimitPerPage) {
		return true
	}

	return false
}

// SetLimitPerPage gets a reference to the given int32 and assigns it to the LimitPerPage field.
func (o *InlineObject1AllOfPageInfo) SetLimitPerPage(v int32) {
	o.LimitPerPage = &v
}

// GetPageExpiresAt returns the PageExpiresAt field value if set, zero value otherwise.
func (o *InlineObject1AllOfPageInfo) GetPageExpiresAt() string {
	if o == nil || IsNil(o.PageExpiresAt) {
		var ret string
		return ret
	}
	return *o.PageExpiresAt
}

// GetPageExpiresAtOk returns a tuple with the PageExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject1AllOfPageInfo) GetPageExpiresAtOk() (*string, bool) {
	if o == nil || IsNil(o.PageExpiresAt) {
		return nil, false
	}
	return o.PageExpiresAt, true
}

// HasPageExpiresAt returns a boolean if a field has been set.
func (o *InlineObject1AllOfPageInfo) HasPageExpiresAt() bool {
	if o != nil && !IsNil(o.PageExpiresAt) {
		return true
	}

	return false
}

// SetPageExpiresAt gets a reference to the given string and assigns it to the PageExpiresAt field.
func (o *InlineObject1AllOfPageInfo) SetPageExpiresAt(v string) {
	o.PageExpiresAt = &v
}

// GetTotalResults returns the TotalResults field value if set, zero value otherwise.
func (o *InlineObject1AllOfPageInfo) GetTotalResults() int32 {
	if o == nil || IsNil(o.TotalResults) {
		var ret int32
		return ret
	}
	return *o.TotalResults
}

// GetTotalResultsOk returns a tuple with the TotalResults field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject1AllOfPageInfo) GetTotalResultsOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalResults) {
		return nil, false
	}
	return o.TotalResults, true
}

// HasTotalResults returns a boolean if a field has been set.
func (o *InlineObject1AllOfPageInfo) HasTotalResults() bool {
	if o != nil && !IsNil(o.TotalResults) {
		return true
	}

	return false
}

// SetTotalResults gets a reference to the given int32 and assigns it to the TotalResults field.
func (o *InlineObject1AllOfPageInfo) SetTotalResults(v int32) {
	o.TotalResults = &v
}

// GetTotalInnerMatches returns the TotalInnerMatches field value if set, zero value otherwise.
func (o *InlineObject1AllOfPageInfo) GetTotalInnerMatches() int32 {
	if o == nil || IsNil(o.TotalInnerMatches) {
		var ret int32
		return ret
	}
	return *o.TotalInnerMatches
}

// GetTotalInnerMatchesOk returns a tuple with the TotalInnerMatches field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject1AllOfPageInfo) GetTotalInnerMatchesOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalInnerMatches) {
		return nil, false
	}
	return o.TotalInnerMatches, true
}

// HasTotalInnerMatches returns a boolean if a field has been set.
func (o *InlineObject1AllOfPageInfo) HasTotalInnerMatches() bool {
	if o != nil && !IsNil(o.TotalInnerMatches) {
		return true
	}

	return false
}

// SetTotalInnerMatches gets a reference to the given int32 and assigns it to the TotalInnerMatches field.
func (o *InlineObject1AllOfPageInfo) SetTotalInnerMatches(v int32) {
	o.TotalInnerMatches = &v
}

// GetNextPageToken returns the NextPageToken field value if set, zero value otherwise.
func (o *InlineObject1AllOfPageInfo) GetNextPageToken() string {
	if o == nil || IsNil(o.NextPageToken) {
		var ret string
		return ret
	}
	return *o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject1AllOfPageInfo) GetNextPageTokenOk() (*string, bool) {
	if o == nil || IsNil(o.NextPageToken) {
		return nil, false
	}
	return o.NextPageToken, true
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *InlineObject1AllOfPageInfo) HasNextPageToken() bool {
	if o != nil && !IsNil(o.NextPageToken) {
		return true
	}

	return false
}

// SetNextPageToken gets a reference to the given string and assigns it to the NextPageToken field.
func (o *InlineObject1AllOfPageInfo) SetNextPageToken(v string) {
	o.NextPageToken = &v
}

// GetPrevPageToken returns the PrevPageToken field value if set, zero value otherwise.
func (o *InlineObject1AllOfPageInfo) GetPrevPageToken() string {
	if o == nil || IsNil(o.PrevPageToken) {
		var ret string
		return ret
	}
	return *o.PrevPageToken
}

// GetPrevPageTokenOk returns a tuple with the PrevPageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject1AllOfPageInfo) GetPrevPageTokenOk() (*string, bool) {
	if o == nil || IsNil(o.PrevPageToken) {
		return nil, false
	}
	return o.PrevPageToken, true
}

// HasPrevPageToken returns a boolean if a field has been set.
func (o *InlineObject1AllOfPageInfo) HasPrevPageToken() bool {
	if o != nil && !IsNil(o.PrevPageToken) {
		return true
	}

	return false
}

// SetPrevPageToken gets a reference to the given string and assigns it to the PrevPageToken field.
func (o *InlineObject1AllOfPageInfo) SetPrevPageToken(v string) {
	o.PrevPageToken = &v
}

func (o InlineObject1AllOfPageInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InlineObject1AllOfPageInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.LimitPerPage) {
		toSerialize["limit_per_page"] = o.LimitPerPage
	}
	if !IsNil(o.PageExpiresAt) {
		toSerialize["page_expires_at"] = o.PageExpiresAt
	}
	if !IsNil(o.TotalResults) {
		toSerialize["total_results"] = o.TotalResults
	}
	if !IsNil(o.TotalInnerMatches) {
		toSerialize["total_inner_matches"] = o.TotalInnerMatches
	}
	if !IsNil(o.NextPageToken) {
		toSerialize["next_page_token"] = o.NextPageToken
	}
	if !IsNil(o.PrevPageToken) {
		toSerialize["prev_page_token"] = o.PrevPageToken
	}
	return toSerialize, nil
}

type NullableInlineObject1AllOfPageInfo struct {
	value *InlineObject1AllOfPageInfo
	isSet bool
}

func (v NullableInlineObject1AllOfPageInfo) Get() *InlineObject1AllOfPageInfo {
	return v.value
}

func (v *NullableInlineObject1AllOfPageInfo) Set(val *InlineObject1AllOfPageInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineObject1AllOfPageInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineObject1AllOfPageInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineObject1AllOfPageInfo(val *InlineObject1AllOfPageInfo) *NullableInlineObject1AllOfPageInfo {
	return &NullableInlineObject1AllOfPageInfo{value: val, isSet: true}
}

func (v NullableInlineObject1AllOfPageInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineObject1AllOfPageInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


