/*
TwelveLabs Video Understanding API

Use the TwelveLabs Video Understanding API to extract information from your videos and make it available to your applications. The API is organized around REST and returns responses in the JSON format. It is compatible with most programming languages, and you can also use Postman or other REST clients to send requests and view responses. 

API version: 1.3.0
Contact: support@twelvelabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package twelvelabs

import (
	"encoding/json"
)

// checks if the StreamEndResponseMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StreamEndResponseMetadata{}

// StreamEndResponseMetadata An object containing metadata about the stream.
type StreamEndResponseMetadata struct {
	// The same unique identifier provided in the `stream_start` event. 
	GenerationId *string `json:"generation_id,omitempty"`
	Usage *TokenUsage `json:"usage,omitempty"`
}

// NewStreamEndResponseMetadata instantiates a new StreamEndResponseMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStreamEndResponseMetadata() *StreamEndResponseMetadata {
	this := StreamEndResponseMetadata{}
	return &this
}

// NewStreamEndResponseMetadataWithDefaults instantiates a new StreamEndResponseMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStreamEndResponseMetadataWithDefaults() *StreamEndResponseMetadata {
	this := StreamEndResponseMetadata{}
	return &this
}

// GetGenerationId returns the GenerationId field value if set, zero value otherwise.
func (o *StreamEndResponseMetadata) GetGenerationId() string {
	if o == nil || IsNil(o.GenerationId) {
		var ret string
		return ret
	}
	return *o.GenerationId
}

// GetGenerationIdOk returns a tuple with the GenerationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StreamEndResponseMetadata) GetGenerationIdOk() (*string, bool) {
	if o == nil || IsNil(o.GenerationId) {
		return nil, false
	}
	return o.GenerationId, true
}

// HasGenerationId returns a boolean if a field has been set.
func (o *StreamEndResponseMetadata) HasGenerationId() bool {
	if o != nil && !IsNil(o.GenerationId) {
		return true
	}

	return false
}

// SetGenerationId gets a reference to the given string and assigns it to the GenerationId field.
func (o *StreamEndResponseMetadata) SetGenerationId(v string) {
	o.GenerationId = &v
}

// GetUsage returns the Usage field value if set, zero value otherwise.
func (o *StreamEndResponseMetadata) GetUsage() TokenUsage {
	if o == nil || IsNil(o.Usage) {
		var ret TokenUsage
		return ret
	}
	return *o.Usage
}

// GetUsageOk returns a tuple with the Usage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StreamEndResponseMetadata) GetUsageOk() (*TokenUsage, bool) {
	if o == nil || IsNil(o.Usage) {
		return nil, false
	}
	return o.Usage, true
}

// HasUsage returns a boolean if a field has been set.
func (o *StreamEndResponseMetadata) HasUsage() bool {
	if o != nil && !IsNil(o.Usage) {
		return true
	}

	return false
}

// SetUsage gets a reference to the given TokenUsage and assigns it to the Usage field.
func (o *StreamEndResponseMetadata) SetUsage(v TokenUsage) {
	o.Usage = &v
}

func (o StreamEndResponseMetadata) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StreamEndResponseMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.GenerationId) {
		toSerialize["generation_id"] = o.GenerationId
	}
	if !IsNil(o.Usage) {
		toSerialize["usage"] = o.Usage
	}
	return toSerialize, nil
}

type NullableStreamEndResponseMetadata struct {
	value *StreamEndResponseMetadata
	isSet bool
}

func (v NullableStreamEndResponseMetadata) Get() *StreamEndResponseMetadata {
	return v.value
}

func (v *NullableStreamEndResponseMetadata) Set(val *StreamEndResponseMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableStreamEndResponseMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableStreamEndResponseMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStreamEndResponseMetadata(val *StreamEndResponseMetadata) *NullableStreamEndResponseMetadata {
	return &NullableStreamEndResponseMetadata{value: val, isSet: true}
}

func (v NullableStreamEndResponseMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStreamEndResponseMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


