/*
TwelveLabs Video Understanding API

Use the TwelveLabs Video Understanding API to extract information from your videos and make it available to your applications. The API is organized around REST and returns responses in the JSON format. It is compatible with most programming languages, and you can also use Postman or other REST clients to send requests and view responses. 

API version: 1.3.0
Contact: support@twelvelabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package twelvelabs

import (
	"encoding/json"
)

// checks if the VideoEmbeddingTaskVideoEmbedding type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VideoEmbeddingTaskVideoEmbedding{}

// VideoEmbeddingTaskVideoEmbedding An object containing the metadata associated with the embedding. 
type VideoEmbeddingTaskVideoEmbedding struct {
	Metadata *VideoEmbeddingMetadata `json:"metadata,omitempty"`
}

// NewVideoEmbeddingTaskVideoEmbedding instantiates a new VideoEmbeddingTaskVideoEmbedding object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVideoEmbeddingTaskVideoEmbedding() *VideoEmbeddingTaskVideoEmbedding {
	this := VideoEmbeddingTaskVideoEmbedding{}
	return &this
}

// NewVideoEmbeddingTaskVideoEmbeddingWithDefaults instantiates a new VideoEmbeddingTaskVideoEmbedding object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVideoEmbeddingTaskVideoEmbeddingWithDefaults() *VideoEmbeddingTaskVideoEmbedding {
	this := VideoEmbeddingTaskVideoEmbedding{}
	return &this
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *VideoEmbeddingTaskVideoEmbedding) GetMetadata() VideoEmbeddingMetadata {
	if o == nil || IsNil(o.Metadata) {
		var ret VideoEmbeddingMetadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoEmbeddingTaskVideoEmbedding) GetMetadataOk() (*VideoEmbeddingMetadata, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *VideoEmbeddingTaskVideoEmbedding) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given VideoEmbeddingMetadata and assigns it to the Metadata field.
func (o *VideoEmbeddingTaskVideoEmbedding) SetMetadata(v VideoEmbeddingMetadata) {
	o.Metadata = &v
}

func (o VideoEmbeddingTaskVideoEmbedding) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VideoEmbeddingTaskVideoEmbedding) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

type NullableVideoEmbeddingTaskVideoEmbedding struct {
	value *VideoEmbeddingTaskVideoEmbedding
	isSet bool
}

func (v NullableVideoEmbeddingTaskVideoEmbedding) Get() *VideoEmbeddingTaskVideoEmbedding {
	return v.value
}

func (v *NullableVideoEmbeddingTaskVideoEmbedding) Set(val *VideoEmbeddingTaskVideoEmbedding) {
	v.value = val
	v.isSet = true
}

func (v NullableVideoEmbeddingTaskVideoEmbedding) IsSet() bool {
	return v.isSet
}

func (v *NullableVideoEmbeddingTaskVideoEmbedding) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVideoEmbeddingTaskVideoEmbedding(val *VideoEmbeddingTaskVideoEmbedding) *NullableVideoEmbeddingTaskVideoEmbedding {
	return &NullableVideoEmbeddingTaskVideoEmbedding{value: val, isSet: true}
}

func (v NullableVideoEmbeddingTaskVideoEmbedding) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVideoEmbeddingTaskVideoEmbedding) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


