/*
TwelveLabs Video Understanding API

Use the TwelveLabs Video Understanding API to extract information from your videos and make it available to your applications. The API is organized around REST and returns responses in the JSON format. It is compatible with most programming languages, and you can also use Postman or other REST clients to send requests and view responses. 

API version: 1.3.0
Contact: support@twelvelabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package twelvelabs

import (
	"encoding/json"
)

// checks if the VideoIndexingTaskSystemMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VideoIndexingTaskSystemMetadata{}

// VideoIndexingTaskSystemMetadata System-generated metadata about the video. 
type VideoIndexingTaskSystemMetadata struct {
	Duration *float32 `json:"duration,omitempty"`
	Filename *string `json:"filename,omitempty"`
	Height *int32 `json:"height,omitempty"`
	Width *int32 `json:"width,omitempty"`
}

// NewVideoIndexingTaskSystemMetadata instantiates a new VideoIndexingTaskSystemMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVideoIndexingTaskSystemMetadata() *VideoIndexingTaskSystemMetadata {
	this := VideoIndexingTaskSystemMetadata{}
	return &this
}

// NewVideoIndexingTaskSystemMetadataWithDefaults instantiates a new VideoIndexingTaskSystemMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVideoIndexingTaskSystemMetadataWithDefaults() *VideoIndexingTaskSystemMetadata {
	this := VideoIndexingTaskSystemMetadata{}
	return &this
}

// GetDuration returns the Duration field value if set, zero value otherwise.
func (o *VideoIndexingTaskSystemMetadata) GetDuration() float32 {
	if o == nil || IsNil(o.Duration) {
		var ret float32
		return ret
	}
	return *o.Duration
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoIndexingTaskSystemMetadata) GetDurationOk() (*float32, bool) {
	if o == nil || IsNil(o.Duration) {
		return nil, false
	}
	return o.Duration, true
}

// HasDuration returns a boolean if a field has been set.
func (o *VideoIndexingTaskSystemMetadata) HasDuration() bool {
	if o != nil && !IsNil(o.Duration) {
		return true
	}

	return false
}

// SetDuration gets a reference to the given float32 and assigns it to the Duration field.
func (o *VideoIndexingTaskSystemMetadata) SetDuration(v float32) {
	o.Duration = &v
}

// GetFilename returns the Filename field value if set, zero value otherwise.
func (o *VideoIndexingTaskSystemMetadata) GetFilename() string {
	if o == nil || IsNil(o.Filename) {
		var ret string
		return ret
	}
	return *o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoIndexingTaskSystemMetadata) GetFilenameOk() (*string, bool) {
	if o == nil || IsNil(o.Filename) {
		return nil, false
	}
	return o.Filename, true
}

// HasFilename returns a boolean if a field has been set.
func (o *VideoIndexingTaskSystemMetadata) HasFilename() bool {
	if o != nil && !IsNil(o.Filename) {
		return true
	}

	return false
}

// SetFilename gets a reference to the given string and assigns it to the Filename field.
func (o *VideoIndexingTaskSystemMetadata) SetFilename(v string) {
	o.Filename = &v
}

// GetHeight returns the Height field value if set, zero value otherwise.
func (o *VideoIndexingTaskSystemMetadata) GetHeight() int32 {
	if o == nil || IsNil(o.Height) {
		var ret int32
		return ret
	}
	return *o.Height
}

// GetHeightOk returns a tuple with the Height field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoIndexingTaskSystemMetadata) GetHeightOk() (*int32, bool) {
	if o == nil || IsNil(o.Height) {
		return nil, false
	}
	return o.Height, true
}

// HasHeight returns a boolean if a field has been set.
func (o *VideoIndexingTaskSystemMetadata) HasHeight() bool {
	if o != nil && !IsNil(o.Height) {
		return true
	}

	return false
}

// SetHeight gets a reference to the given int32 and assigns it to the Height field.
func (o *VideoIndexingTaskSystemMetadata) SetHeight(v int32) {
	o.Height = &v
}

// GetWidth returns the Width field value if set, zero value otherwise.
func (o *VideoIndexingTaskSystemMetadata) GetWidth() int32 {
	if o == nil || IsNil(o.Width) {
		var ret int32
		return ret
	}
	return *o.Width
}

// GetWidthOk returns a tuple with the Width field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoIndexingTaskSystemMetadata) GetWidthOk() (*int32, bool) {
	if o == nil || IsNil(o.Width) {
		return nil, false
	}
	return o.Width, true
}

// HasWidth returns a boolean if a field has been set.
func (o *VideoIndexingTaskSystemMetadata) HasWidth() bool {
	if o != nil && !IsNil(o.Width) {
		return true
	}

	return false
}

// SetWidth gets a reference to the given int32 and assigns it to the Width field.
func (o *VideoIndexingTaskSystemMetadata) SetWidth(v int32) {
	o.Width = &v
}

func (o VideoIndexingTaskSystemMetadata) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VideoIndexingTaskSystemMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Duration) {
		toSerialize["duration"] = o.Duration
	}
	if !IsNil(o.Filename) {
		toSerialize["filename"] = o.Filename
	}
	if !IsNil(o.Height) {
		toSerialize["height"] = o.Height
	}
	if !IsNil(o.Width) {
		toSerialize["width"] = o.Width
	}
	return toSerialize, nil
}

type NullableVideoIndexingTaskSystemMetadata struct {
	value *VideoIndexingTaskSystemMetadata
	isSet bool
}

func (v NullableVideoIndexingTaskSystemMetadata) Get() *VideoIndexingTaskSystemMetadata {
	return v.value
}

func (v *NullableVideoIndexingTaskSystemMetadata) Set(val *VideoIndexingTaskSystemMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableVideoIndexingTaskSystemMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableVideoIndexingTaskSystemMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVideoIndexingTaskSystemMetadata(val *VideoIndexingTaskSystemMetadata) *NullableVideoIndexingTaskSystemMetadata {
	return &NullableVideoIndexingTaskSystemMetadata{value: val, isSet: true}
}

func (v NullableVideoIndexingTaskSystemMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVideoIndexingTaskSystemMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


