/*
TwelveLabs Video Understanding API

Use the TwelveLabs Video Understanding API to extract information from your videos and make it available to your applications. The API is organized around REST and returns responses in the JSON format. It is compatible with most programming languages, and you can also use Postman or other REST clients to send requests and view responses. 

API version: 1.3.0
Contact: support@twelvelabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package twelvelabs

import (
	"encoding/json"
)

// checks if the InlineObject16PageInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InlineObject16PageInfo{}

// InlineObject16PageInfo An object that provides information about pagination. 
type InlineObject16PageInfo struct {
	// The maximum number of items on each page.
	LimitPerPage *int32 `json:"limit_per_page,omitempty"`
	// The page you retrieved.
	Page *int32 `json:"page,omitempty"`
	// The total number of pages.
	TotalPage *int32 `json:"total_page,omitempty"`
	// The total number of results.
	TotalResults *int32 `json:"total_results,omitempty"`
}

// NewInlineObject16PageInfo instantiates a new InlineObject16PageInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineObject16PageInfo() *InlineObject16PageInfo {
	this := InlineObject16PageInfo{}
	return &this
}

// NewInlineObject16PageInfoWithDefaults instantiates a new InlineObject16PageInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineObject16PageInfoWithDefaults() *InlineObject16PageInfo {
	this := InlineObject16PageInfo{}
	return &this
}

// GetLimitPerPage returns the LimitPerPage field value if set, zero value otherwise.
func (o *InlineObject16PageInfo) GetLimitPerPage() int32 {
	if o == nil || IsNil(o.LimitPerPage) {
		var ret int32
		return ret
	}
	return *o.LimitPerPage
}

// GetLimitPerPageOk returns a tuple with the LimitPerPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject16PageInfo) GetLimitPerPageOk() (*int32, bool) {
	if o == nil || IsNil(o.LimitPerPage) {
		return nil, false
	}
	return o.LimitPerPage, true
}

// HasLimitPerPage returns a boolean if a field has been set.
func (o *InlineObject16PageInfo) HasLimitPerPage() bool {
	if o != nil && !IsNil(o.LimitPerPage) {
		return true
	}

	return false
}

// SetLimitPerPage gets a reference to the given int32 and assigns it to the LimitPerPage field.
func (o *InlineObject16PageInfo) SetLimitPerPage(v int32) {
	o.LimitPerPage = &v
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *InlineObject16PageInfo) GetPage() int32 {
	if o == nil || IsNil(o.Page) {
		var ret int32
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject16PageInfo) GetPageOk() (*int32, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *InlineObject16PageInfo) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given int32 and assigns it to the Page field.
func (o *InlineObject16PageInfo) SetPage(v int32) {
	o.Page = &v
}

// GetTotalPage returns the TotalPage field value if set, zero value otherwise.
func (o *InlineObject16PageInfo) GetTotalPage() int32 {
	if o == nil || IsNil(o.TotalPage) {
		var ret int32
		return ret
	}
	return *o.TotalPage
}

// GetTotalPageOk returns a tuple with the TotalPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject16PageInfo) GetTotalPageOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalPage) {
		return nil, false
	}
	return o.TotalPage, true
}

// HasTotalPage returns a boolean if a field has been set.
func (o *InlineObject16PageInfo) HasTotalPage() bool {
	if o != nil && !IsNil(o.TotalPage) {
		return true
	}

	return false
}

// SetTotalPage gets a reference to the given int32 and assigns it to the TotalPage field.
func (o *InlineObject16PageInfo) SetTotalPage(v int32) {
	o.TotalPage = &v
}

// GetTotalResults returns the TotalResults field value if set, zero value otherwise.
func (o *InlineObject16PageInfo) GetTotalResults() int32 {
	if o == nil || IsNil(o.TotalResults) {
		var ret int32
		return ret
	}
	return *o.TotalResults
}

// GetTotalResultsOk returns a tuple with the TotalResults field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject16PageInfo) GetTotalResultsOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalResults) {
		return nil, false
	}
	return o.TotalResults, true
}

// HasTotalResults returns a boolean if a field has been set.
func (o *InlineObject16PageInfo) HasTotalResults() bool {
	if o != nil && !IsNil(o.TotalResults) {
		return true
	}

	return false
}

// SetTotalResults gets a reference to the given int32 and assigns it to the TotalResults field.
func (o *InlineObject16PageInfo) SetTotalResults(v int32) {
	o.TotalResults = &v
}

func (o InlineObject16PageInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InlineObject16PageInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.LimitPerPage) {
		toSerialize["limit_per_page"] = o.LimitPerPage
	}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !IsNil(o.TotalPage) {
		toSerialize["total_page"] = o.TotalPage
	}
	if !IsNil(o.TotalResults) {
		toSerialize["total_results"] = o.TotalResults
	}
	return toSerialize, nil
}

type NullableInlineObject16PageInfo struct {
	value *InlineObject16PageInfo
	isSet bool
}

func (v NullableInlineObject16PageInfo) Get() *InlineObject16PageInfo {
	return v.value
}

func (v *NullableInlineObject16PageInfo) Set(val *InlineObject16PageInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineObject16PageInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineObject16PageInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineObject16PageInfo(val *InlineObject16PageInfo) *NullableInlineObject16PageInfo {
	return &NullableInlineObject16PageInfo{value: val, isSet: true}
}

func (v NullableInlineObject16PageInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineObject16PageInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


