/*
TwelveLabs Video Understanding API

Use the TwelveLabs Video Understanding API to extract information from your videos and make it available to your applications. The API is organized around REST and returns responses in the JSON format. It is compatible with most programming languages, and you can also use Postman or other REST clients to send requests and view responses. 

API version: 1.3.0
Contact: support@twelvelabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package twelvelabs

import (
	"encoding/json"
)

// checks if the InlineObject20FailedFilesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InlineObject20FailedFilesInner{}

// InlineObject20FailedFilesInner struct for InlineObject20FailedFilesInner
type InlineObject20FailedFilesInner struct {
	// The filename of the video that failed to be imported.
	Filename *string `json:"filename,omitempty"`
	// The error message if the import failed.
	ErrorMessage *string `json:"error_message,omitempty"`
}

// NewInlineObject20FailedFilesInner instantiates a new InlineObject20FailedFilesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineObject20FailedFilesInner() *InlineObject20FailedFilesInner {
	this := InlineObject20FailedFilesInner{}
	return &this
}

// NewInlineObject20FailedFilesInnerWithDefaults instantiates a new InlineObject20FailedFilesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineObject20FailedFilesInnerWithDefaults() *InlineObject20FailedFilesInner {
	this := InlineObject20FailedFilesInner{}
	return &this
}

// GetFilename returns the Filename field value if set, zero value otherwise.
func (o *InlineObject20FailedFilesInner) GetFilename() string {
	if o == nil || IsNil(o.Filename) {
		var ret string
		return ret
	}
	return *o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject20FailedFilesInner) GetFilenameOk() (*string, bool) {
	if o == nil || IsNil(o.Filename) {
		return nil, false
	}
	return o.Filename, true
}

// HasFilename returns a boolean if a field has been set.
func (o *InlineObject20FailedFilesInner) HasFilename() bool {
	if o != nil && !IsNil(o.Filename) {
		return true
	}

	return false
}

// SetFilename gets a reference to the given string and assigns it to the Filename field.
func (o *InlineObject20FailedFilesInner) SetFilename(v string) {
	o.Filename = &v
}

// GetErrorMessage returns the ErrorMessage field value if set, zero value otherwise.
func (o *InlineObject20FailedFilesInner) GetErrorMessage() string {
	if o == nil || IsNil(o.ErrorMessage) {
		var ret string
		return ret
	}
	return *o.ErrorMessage
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject20FailedFilesInner) GetErrorMessageOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorMessage) {
		return nil, false
	}
	return o.ErrorMessage, true
}

// HasErrorMessage returns a boolean if a field has been set.
func (o *InlineObject20FailedFilesInner) HasErrorMessage() bool {
	if o != nil && !IsNil(o.ErrorMessage) {
		return true
	}

	return false
}

// SetErrorMessage gets a reference to the given string and assigns it to the ErrorMessage field.
func (o *InlineObject20FailedFilesInner) SetErrorMessage(v string) {
	o.ErrorMessage = &v
}

func (o InlineObject20FailedFilesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InlineObject20FailedFilesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Filename) {
		toSerialize["filename"] = o.Filename
	}
	if !IsNil(o.ErrorMessage) {
		toSerialize["error_message"] = o.ErrorMessage
	}
	return toSerialize, nil
}

type NullableInlineObject20FailedFilesInner struct {
	value *InlineObject20FailedFilesInner
	isSet bool
}

func (v NullableInlineObject20FailedFilesInner) Get() *InlineObject20FailedFilesInner {
	return v.value
}

func (v *NullableInlineObject20FailedFilesInner) Set(val *InlineObject20FailedFilesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineObject20FailedFilesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineObject20FailedFilesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineObject20FailedFilesInner(val *InlineObject20FailedFilesInner) *NullableInlineObject20FailedFilesInner {
	return &NullableInlineObject20FailedFilesInner{value: val, isSet: true}
}

func (v NullableInlineObject20FailedFilesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineObject20FailedFilesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


