/*
TwelveLabs Video Understanding API

Testing ManageVideosAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package twelvelabs

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/xyberii4/lec-assist/backend/pkg/twelvelabs"
)

func Test_twelvelabs_ManageVideosAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ManageVideosAPIService DeleteVideoInformation", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var indexId string
		var videoId string

		httpRes, err := apiClient.ManageVideosAPI.DeleteVideoInformation(context.Background(), indexId, videoId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ManageVideosAPIService ListVideos", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var indexId string

		resp, httpRes, err := apiClient.ManageVideosAPI.ListVideos(context.Background(), indexId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ManageVideosAPIService RetrieveVideoInformation", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var indexId string
		var videoId string

		resp, httpRes, err := apiClient.ManageVideosAPI.RetrieveVideoInformation(context.Background(), indexId, videoId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ManageVideosAPIService UpdateVideoInformation", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var indexId string
		var videoId string

		httpRes, err := apiClient.ManageVideosAPI.UpdateVideoInformation(context.Background(), indexId, videoId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
