/*
TwelveLabs Video Understanding API

Testing UploadVideosAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package twelvelabs

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/xyberii4/lec-assist/backend/pkg/twelvelabs"
)

func Test_twelvelabs_UploadVideosAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test UploadVideosAPIService CloudToCloudImportVideos", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var integrationId string

		resp, httpRes, err := apiClient.UploadVideosAPI.CloudToCloudImportVideos(context.Background(), integrationId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UploadVideosAPIService CloudToCloudRetrieveImportLogs", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var integrationId string

		resp, httpRes, err := apiClient.UploadVideosAPI.CloudToCloudRetrieveImportLogs(context.Background(), integrationId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UploadVideosAPIService CloudToCloudRetrieveStatus", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var integrationId string

		resp, httpRes, err := apiClient.UploadVideosAPI.CloudToCloudRetrieveStatus(context.Background(), integrationId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UploadVideosAPIService CreateVideoIndexingTask", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.UploadVideosAPI.CreateVideoIndexingTask(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UploadVideosAPIService DeleteVideoIndexingTask", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var taskId string

		httpRes, err := apiClient.UploadVideosAPI.DeleteVideoIndexingTask(context.Background(), taskId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UploadVideosAPIService ListVideoIndexingTasks", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.UploadVideosAPI.ListVideoIndexingTasks(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UploadVideosAPIService RetrieveVideoIndexingTask", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var taskId string

		resp, httpRes, err := apiClient.UploadVideosAPI.RetrieveVideoIndexingTask(context.Background(), taskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
