/*
TwelveLabs Video Understanding API

Testing AnyToVideoSearchAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package twelvelabs

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/xyberii4/lec-assist/backend/pkg/twelvelabs"
)

func Test_twelvelabs_AnyToVideoSearchAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AnyToVideoSearchAPIService AnyToVideoRetrieveSpecificPage", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pageToken string

		resp, httpRes, err := apiClient.AnyToVideoSearchAPI.AnyToVideoRetrieveSpecificPage(context.Background(), pageToken).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AnyToVideoSearchAPIService AnyToVideoSearch", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AnyToVideoSearchAPI.AnyToVideoSearch(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
